function foot = calc_foot_point(m, foot_ad_struct)
    foot = (foot_ad_struct.t + foot_ad_struct.e) / 2 + ...
        1 * norm(foot_ad_struct.e - foot_ad_struct.t) * ( ...
        foot_ad_struct.t - m) / norm(foot_ad_struct.t - m);
end