function EKF_G = create_EKF_G(dt_G, resolution, q2, r_diag, x_G)
    F_func = @(x_G_, dt) [1, dt, dt^2/2; 0, 1, dt; 0, 0, 1] * x_G_;
    y_func = @(x_G_) x_G_;
    Q_func = @(q2, dt) [dt^4/4, dt^3/2, dt^2/2; dt^3/2, dt^2, dt; dt^2/2, dt, 1] * q2 * resolution^2;
    R = diag(r_diag) * resolution^2;

    EKF_G = extendedKalmanFilter( ...
        @(x_G_) F_func(x_G_, dt_G), ...
        @(x_G_) y_func(x_G_), ...
        x_G, ...
        'ProcessNoise', Q_func(q2, dt_G), ...
        'MeasurementNoise', R, ...
        'StateCovariance', [] ...
        );
end